# Generated by Django 3.0 on 2025-02-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('latitude', models.CharField(max_length=500)),
                ('longitude', models.CharField(max_length=500)),
                ('merchant_latitude', models.CharField(max_length=500)),
                ('merchant_longitude', models.CharField(max_length=500)),
                ('jobs', models.CharField(max_length=500)),
                ('prediction', models.CharField(max_length=500)),
            ],
        ),
    ]
